times = ("Botafogo", "Forteleza", "Palmeiras", "Flamengo", "Bahia", "São Paulo", "Cruzeiro", "Atlético-MG", "Athletico-PR", "Vasco da Gama", "Juventude", "Bragantino", "Internacional", "Criciúma", "Grêmio", "Vitória", "Corinthians", "Fluminense", "Cuiabá", "Atlético  Goianiense")
print("-=" * 20)
print(f"Lista de times do Brasileirão: {times}")
print("-=" * 20)
print(f"Os 5 primeiros são {times[:5]}")
print("-=" * 20)
print(f"Os 4 últimos são {times[16:]}")
print("-=" * 20)
print(f"Times em ordem alfabética: {sorted(times)}")
print("-=" * 20)
print(f"O Vasco da Gama está na {(times.index("Vasco da Gama"))+1}º posição")